// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.30.2
// source: proto/heart.proto

package heartpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WriteRequest  bool                   `protobuf:"varint,1,opt,name=write_request,json=writeRequest,proto3" json:"write_request,omitempty"`
	Sql           string                 `protobuf:"bytes,2,opt,name=sql,proto3" json:"sql,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Args          []*anypb.Any           `protobuf:"bytes,5,rep,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_proto_heart_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_proto_heart_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_proto_heart_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetWriteRequest() bool {
	if x != nil {
		return x.WriteRequest
	}
	return false
}

func (x *Request) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

func (x *Request) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Request) GetArgs() []*anypb.Any {
	if x != nil {
		return x.Args
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       string                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	NodeId        uint32                 `protobuf:"varint,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_proto_heart_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_heart_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_proto_heart_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Response) GetNodeId() uint32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

var File_proto_heart_proto protoreflect.FileDescriptor

const file_proto_heart_proto_rawDesc = "" +
	"\n" +
	"\x11proto/heart.proto\x12\x05heart\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19google/protobuf/any.proto\"\xa4\x01\n" +
	"\aRequest\x12#\n" +
	"\rwrite_request\x18\x01 \x01(\bR\fwriteRequest\x12\x10\n" +
	"\x03sql\x18\x02 \x01(\tR\x03sql\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12(\n" +
	"\x04args\x18\x05 \x03(\v2\x14.google.protobuf.AnyR\x04args\"W\n" +
	"\bResponse\x12\x18\n" +
	"\apayload\x18\x01 \x01(\tR\apayload\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\rR\x06nodeId21\n" +
	"\x05Heart\x12(\n" +
	"\x05Route\x12\x0e.heart.Request\x1a\x0f.heart.ResponseB\vZ\t./heartpbb\x06proto3"

var (
	file_proto_heart_proto_rawDescOnce sync.Once
	file_proto_heart_proto_rawDescData []byte
)

func file_proto_heart_proto_rawDescGZIP() []byte {
	file_proto_heart_proto_rawDescOnce.Do(func() {
		file_proto_heart_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_heart_proto_rawDesc), len(file_proto_heart_proto_rawDesc)))
	})
	return file_proto_heart_proto_rawDescData
}

var file_proto_heart_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_heart_proto_goTypes = []any{
	(*Request)(nil),               // 0: heart.Request
	(*Response)(nil),              // 1: heart.Response
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
	(*anypb.Any)(nil),             // 3: google.protobuf.Any
}
var file_proto_heart_proto_depIdxs = []int32{
	2, // 0: heart.Request.timestamp:type_name -> google.protobuf.Timestamp
	3, // 1: heart.Request.args:type_name -> google.protobuf.Any
	0, // 2: heart.Heart.Route:input_type -> heart.Request
	1, // 3: heart.Heart.Route:output_type -> heart.Response
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_heart_proto_init() }
func file_proto_heart_proto_init() {
	if File_proto_heart_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_heart_proto_rawDesc), len(file_proto_heart_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_heart_proto_goTypes,
		DependencyIndexes: file_proto_heart_proto_depIdxs,
		MessageInfos:      file_proto_heart_proto_msgTypes,
	}.Build()
	File_proto_heart_proto = out.File
	file_proto_heart_proto_goTypes = nil
	file_proto_heart_proto_depIdxs = nil
}
