// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: proto/heart.proto

package heartpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Heart_Route_FullMethodName = "/heart.Heart/Route"
)

// HeartClient is the client API for Heart service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HeartClient interface {
	Route(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type heartClient struct {
	cc grpc.ClientConnInterface
}

func NewHeartClient(cc grpc.ClientConnInterface) HeartClient {
	return &heartClient{cc}
}

func (c *heartClient) Route(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, Heart_Route_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HeartServer is the server API for Heart service.
// All implementations must embed UnimplementedHeartServer
// for forward compatibility.
type HeartServer interface {
	Route(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedHeartServer()
}

// UnimplementedHeartServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHeartServer struct{}

func (UnimplementedHeartServer) Route(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Route not implemented")
}
func (UnimplementedHeartServer) mustEmbedUnimplementedHeartServer() {}
func (UnimplementedHeartServer) testEmbeddedByValue()               {}

// UnsafeHeartServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HeartServer will
// result in compilation errors.
type UnsafeHeartServer interface {
	mustEmbedUnimplementedHeartServer()
}

func RegisterHeartServer(s grpc.ServiceRegistrar, srv HeartServer) {
	// If the following call pancis, it indicates UnimplementedHeartServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Heart_ServiceDesc, srv)
}

func _Heart_Route_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HeartServer).Route(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Heart_Route_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HeartServer).Route(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Heart_ServiceDesc is the grpc.ServiceDesc for Heart service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Heart_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "heart.Heart",
	HandlerType: (*HeartServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Route",
			Handler:    _Heart_Route_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/heart.proto",
}
