# Heart service configuration
addr: "localhost:8080"
rabbitmq_url: "amqp://guest:guest@localhost:5672/"
exchange: "leviathan_writes"
queue_name: "write_requests"

# Node addresses for load balancing
nodes:
  - "localhost:9001"

# Health checking configuration
health_check_interval: "30s"  # How often to check node health
health_check_timeout: "5s"    # Timeout for health check requests

# Request handling configuration
max_retries: 3                # Maximum retry attempts for failed requests
request_timeout: "30s"        # Timeout for client requests
